---
- name: Dependências
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Instalar pip3
  apt:
    name: python3-pip
    state: present

- name: Instalar Docker SDK for Python
  pip:
    name: docker
    executable: pip3

- name: Chave GPG
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Repositório Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker

- name: Atualizar APT
  apt:
    update_cache: yes

- name: Instalar Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Habilitar Docker
  service:
    name: docker
    state: started
    enabled: yes
