---
- name: Remover todos os containers Docker
  hosts: docker
  become: yes

  tasks:
    - name: Dar permissão
      file:
        path: /vagrant/ansible/scripts/delete_all.sh
        mode: '0755'

    - name: Executar script para remover todos os containers
      shell: /vagrant/ansible/scripts/delete_all.sh
      register: delete_output

    - name: Exibir Output
      debug:
        var: delete_output.stdout_lines
